# Generated by Django 5.0.2 on 2024-02-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('idMiembro', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMiembro', models.CharField(max_length=255)),
                ('apellidoMiembro', models.CharField(max_length=255)),
            ],
        ),
    ]
